name: Flipsite Example Site
description: A site that shows how easy and fast it is to create Flipsite sites
theme: $theme.yaml
social:
  facebook: flipsiteio
  twitter: flipsiteio
  email: info@flipsite.io
  phone: +358503828498
pages:
  home:
    -
      picture: flipsite.svg
      heading: Build websites in minutes that score 100% on speed, SEO and accessibility.
      lead: |
        Build an entire website in YAML and understand it at a glance. Flipsite is a static/dynamic
        compiler for beautiful HTML & CSS & resources that are structured, fast, minimal and
        accessible.
      buttons.0:
        type: primary
        text: Get started
        url: https://github.com/flipsite/flipsite
      style: ${theme.style.hero}